# Sofle FT - buduje 5 firmware:
#   - lewa OLED + Studio
#   - lewa nice!view + Studio
#   - prawa OLED
#   - prawa nice!view
#   - settings_reset (do wyczyszczenia BLE)
#
# Wybierasz UF2 do flashowania w zależności od tego co masz fizycznie podlutowane.
---
include:
  # Lewa z OLED
  - board: nice_nano//zmk
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left_oled
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/zmk-modules/persistent_layer"
  # Lewa z nice!view
  - board: nice_nano//zmk
    shield: sofle_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left_niceview
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/zmk-modules/persistent_layer"
  # Prawa z OLED
  - board: nice_nano//zmk
    shield: sofle_right
    artifact-name: sofle_right_oled
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/zmk-modules/persistent_layer"
  # Prawa z nice!view
  - board: nice_nano//zmk
    shield: sofle_right nice_view_adapter nice_view
    artifact-name: sofle_right_niceview
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/zmk-modules/persistent_layer"
  # Reset
  - board: nice_nano//zmk
    shield: settings_reset
